library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fileInput(inputId = "markersInput",
                label = "Upload a .csv file of differentially expressed
                markers generated by the R package Seurat",
                accept = c(".csv")),
      textOutput(outputId = "downloadReady"),
      br(),
      downloadButton('downloadData', 'Download'),
      tags$div(style = "height: 100px;"),
      fileInput(inputId = "filesInput",
                label = "Upload DAVID output files (tab-delimited txt files)",
                accept = c(".txt"),
                multiple = TRUE),
      tags$div(style = "height: 250px;"),
    ),
    mainPanel(
      plotOutput("heatmap")
    )
  )
)

server <- function(input, output, session) {

  data <- reactiveVal(NULL)
  genes_list <- reactiveVal(NULL)
  ready <- reactiveVal(NULL)
  uploaded_files <- reactiveVal(NULL)
  top_heatmap <- reactiveVal(NULL)

  observeEvent(input$markersInput, {
    shiny::req(input$markersInput)
    markers_df <- read.csv(input$markersInput$datapath)
    separated_clusters <- SeuratToGO::separate_clusters(markers_df)
    genes_list(separated_clusters)
    ready("Your file is ready to be downloaded!")
    # data(markers_df)
  })

  observeEvent(input$filesInput, {
    req(input$filesInput)
    # Assuming the uploaded files are in a list
    files = input$filesInput$name
    print(files)
    uploaded_files(files)

    dir_name <- "david"
    if (dir.exists(dir_name)) {
      unlink(dir_name, recursive = TRUE)
    }
    dir.create(dir_name, showWarnings = FALSE)
    file.copy(input$filesInput$datapath, file.path(dir_name, files),
              overwrite = TRUE)
    david_combined <- SeuratToGO::combine_david_files(file.path(dir_name))
    top_processes <- SeuratToGO::get_all_top_processes(david_combined)
    heatmap <- SeuratToGO::top_processes_heatmap(top_processes)
    top_heatmap(heatmap)
    unlink(dir_name, recursive = TRUE)

  })

  output$downloadReady <- renderText({
    req(ready())
    ready()
  })

  output$heatmap <- renderPlot({
    req(top_heatmap())
    # Display a summary of the uploaded files
    top_heatmap()
  })

  output$downloadData <- downloadHandler(
    filename = function() {
      "genes_list.txt"
    },
    content = function(file) {
      #req(data())
      req(genes_list())
      #separated_clusters <- SeuratToGO::separate_clusters(data())
      write.table(genes_list(), file, sep = "\t", row.names = FALSE,
                  quote = FALSE)
    }
  )

}

shiny::shinyApp(ui = ui, server = server)
