library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fileInput(inputId = "markersInput",
                label = "Upload a .csv file of differentially expressed
                markers generated by the R package Seurat",
                accept = c(".csv")),
      downloadButton('downloadData', 'Download')
    ),
    mainPanel(
    )
  )
)

server <- function(input, output, session) {

  data <- reactiveVal(NULL)

  observeEvent(input$markersInput, {
    shiny::req(input$markersInput)
    markers_df <- read.csv(input$markersInput$datapath)
    data(markers_df)
  })

  output$downloadData <- downloadHandler(
    filename = function() {
      "genes_list.txt"
    },
    content = function(file) {
      req(data())
      separated_clusters <- SeuratToGO::separate_clusters(data())
      write.table(separated_clusters, file, sep = "\t", row.names = FALSE,
                  quote = FALSE)
    }
  )

}

shiny::shinyApp(ui = ui, server = server)
