library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fileInput(inputId = "markersInput",
                label = "Upload a .csv file of differentially expressed
                markers generated by the R package Seurat",
                accept = c(".csv")),
      textOutput(outputId = "downloadReady"),
      br(),
      downloadButton('downloadData', 'Download'),
      tags$div(style = "height: 100px;"),
      fileInput(inputId = "filesInput",
                label = "Upload DAVID output files (tab-delimited .txt files)",
                accept = c(".txt"),
                multiple = TRUE),
      numericInput(inputId = "benjamini",
                   label = "Benjamini number threshold",
                   value = 0.05,
                   min = 0),
      numericInput(inputId = "top_n",
                   label = "Top number of processes per cluster",
                   value = 5,
                   min = 1),
      actionButton(inputId = "heatmap",
                   label = "Generate heatmap"),
      tags$div(style = "height: 250px;"),
    ),
    mainPanel(
      plotOutput("heatmap")
    )
  )
)

server <- function(input, output, session) {

  genes_list <- reactiveVal(NULL)
  ready <- reactiveVal(NULL)
  uploaded_files <- reactiveVal(NULL)
  top_heatmap <- reactiveVal(NULL)

  # file input trigger
  observeEvent(input$markersInput, {
    shiny::req(input$markersInput)
    markers_df <- read.csv(input$markersInput$datapath)
    separated_clusters <- SeuratToGO::separate_clusters(markers_df)
    genes_list(separated_clusters)
    ready("Your file is ready to be downloaded!")
  })

  # when "Generate heatmap" button is clicked
  observeEvent(input$heatmap, {
    # check that there is value input
    if (is.null(input$filesInput)) {
      showModal(modalDialog(
        title = "Error",
        "Please upload DAVID output files",
        easyClose = TRUE
      ))
    }
    # check benjamini field
    if (is.na(input$benjamini) || input$benjamini == "") {
      showModal(modalDialog(
        title = "Error",
        "Please enter a threshold for benjamini value",
        easyClose = TRUE
      ))
    }
    # check top_n field
    if (is.na(input$top_n) || input$benjamini == "") {
      showModal(modalDialog(
        title = "Error",
        "Please enter a number for the top number of processes per cluster",
        easyClose = TRUE
      ))
    }
    req(input$benjamini)
    req(input$filesInput)
    req(input$top_n)

    # Uploaded files are in a list
    files = input$filesInput$name
    uploaded_files(files)


    dir_name <- "david"
    if (dir.exists(dir_name)) {
      unlink(dir_name, recursive = TRUE)
    }
    # create temp directory to put uploaded DAVID files
    dir.create(dir_name, showWarnings = FALSE)
    file.copy(input$filesInput$datapath, file.path(dir_name, files),
              overwrite = TRUE)
    david_combined <- SeuratToGO::combine_david_files(file.path(dir_name))
    top_processes <- SeuratToGO::get_all_top_processes(david_combined,
                                                       input$benjamini,
                                                       input$top_n)
    heatmap <- SeuratToGO::top_processes_heatmap(top_processes,
                                                 input$benjamini,
                                                 input$top_n)
    top_heatmap(heatmap)
    # delete temp directory so next call is not affected
    unlink(dir_name, recursive = TRUE)

  })

  output$downloadReady <- renderText({
    req(ready())
    ready()
  })

  output$heatmap <- renderPlot({
    req(top_heatmap())
    top_heatmap()
  })

  output$downloadData <- downloadHandler(
    filename = function() {
      "genes_list.txt"
    },
    content = function(file) {
      req(genes_list())
      write.table(genes_list(), file, sep = "\t", row.names = FALSE,
                  quote = FALSE)
    }
  )

}

shiny::shinyApp(ui = ui, server = server)
